language: python
python:
  - "3.6.1"

services:
  - postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database test_db;' -U postgres
  - export  TESTING_DATABASE=test_db

# command to run tests
script: 
- pytest --cov=.
after_success:
- coveralls