language: python
python:

  - "3.6.1"
services:
  - postgres
# command to install dependencies
install:
  - pip install -r requirements.txt
  - psql -c 'create database SendIT;' -U postgres
# command to run tests
script: 
- pytest  --cov=.
- coverage
- coverage report
after_success:
- coveralls